baseURL = "https://alparslanba.github.io/Final_Social_Data/"
languageCode = 'en-us'
title = 'Wildfires in the US'
theme = "ananke"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
    fullWidthTheme = true
    themeColor = "red"
    Toc = true